name: Deploy with Terraform

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Find where your Terraform files are located
      - name: List files (for debugging)
        run: ls -R

      # Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Change to the directory containing your Terraform files if they're not in root
      # - name: Change directory
      #   run: cd path/to/terraform/files && echo "::set-output name=dir::$(pwd)"
      #   id: change-dir

      # Terraform Init
      - name: Terraform Init
        run: terraform init
        # If your files are in a subdirectory, use:
        # run: cd path/to/terraform/files && terraform init

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate
        # If your files are in a subdirectory, use:
        # run: cd path/to/terraform/files && terraform validate

      # Terraform Plan
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        # If your files are in a subdirectory, use:
        # run: cd path/to/terraform/files && terraform plan -out=tfplan

      # Terraform Apply (only on master)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve tfplan
        # If your files are in a subdirectory, use:
        # run: cd path/to/terraform/files && terraform apply -auto-approve tfplan
