name: Deploy with Terraform

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Create Terraform configuration file
      - name: Create Terraform configuration
        run: |
          echo 'provider "aws" { region = "us-west-2" }' > main.tf
          echo 'resource "aws_s3_bucket" "my_bucket" { bucket = "my-unique-bucket-name" acl = "private" }' >> main.tf
          echo 'output "bucket_name" { value = aws_s3_bucket.my_bucket.bucket }' >> main.tf

      # Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Terraform Plan
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      # Terraform Apply (only on main)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve tfplan
