Here is the indented code:


name: Deploy with Terraform

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Create a simple Terraform config (local provider)
      - name: Generate Terraform config
        run: |
          cat <<EOF > main.tf
          # Simple local file example (no cloud provider needed)
          resource "local_file" "test_file" {
            filename = "terraform_output.txt"
            content  = "This file was created by Terraform in GitHub Actions!"
          }

          output "file_message" {
            value = local_file.test_file.content
          }
          EOF

      # Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Initialize & validate
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      # Plan and Apply
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      # (Optional) Show the created file
      - name: Display Terraform Output
        run: cat terraform_output.txt
```
